name: Build NEolgd

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Clone NEolgd
        run: |
          git clone https://github.com/neologd/mecab-ipadic-neologd.git
      - name: Make NEologd
        run: |
          ./libexec/make-mecab-ipadic-neologd.sh || echo "made NEologd!"
        working-directory: mecab-ipadic-neologd
